apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-svc
subsets:
  - addresses:
      - ip: 192.168.3.50
    ports:
      - port: 3306