spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        include-not-ready-addresses: true
      loadbalancer:
        mode: SERVICE

logging:
  level:
    com:
      codyzeng:
        k8s:
          examples:
            sd:
              ExampleFeignClient: DEBUG
    org:
      springframework:
        cloud:
          client:
            loadbalancer: DEBUG


# feign相关配置
feign:
  client:
    # 配置
    config:
      # feign.Request.Options.Options()
      default:
        # 控制日志Level，默认：null即NONE
        # NONE 没有日志
        # BASIC 只记录请求方法和URL以及响应状态码和执行时间
        # HEADERS 记录基本信息以及请求和响应头
        # FULL 记录请求和响应的头、正文和元数据
        logger-level: FULL
