spec:
  template:
    spec:
      serviceAccount: ${project.artifactId}
      initContainers:
        - name: init-env
          command: [ "/bin/sh", "-c", "env" ]
          image: busybox
          envFrom:
            - secretRef:
                name: ${project.artifactId}
      containers:
        - env:
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: ${project.artifactId}
                  key: spring.datasource.username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: ${project.artifactId}
                  key: spring.datasource.password


